/* Generated By:JavaCC: Do not edit this line. ERsConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ERsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int L = 6;
  /** RegularExpression Id. */
  int LLOW = 7;
  /** RegularExpression Id. */
  int LHIGH = 8;
  /** RegularExpression Id. */
  int D = 9;
  /** RegularExpression Id. */
  int DNN = 10;
  /** RegularExpression Id. */
  int INT_TYPE = 11;
  /** RegularExpression Id. */
  int UINT_TYPE = 12;
  /** RegularExpression Id. */
  int FLOAT_TYPE = 13;
  /** RegularExpression Id. */
  int CHAR_TYPE = 14;
  /** RegularExpression Id. */
  int BOOL_TYPE = 15;
  /** RegularExpression Id. */
  int INT64 = 16;
  /** RegularExpression Id. */
  int INT32 = 17;
  /** RegularExpression Id. */
  int INT16 = 18;
  /** RegularExpression Id. */
  int INT8 = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int UINT64 = 21;
  /** RegularExpression Id. */
  int UINT32 = 22;
  /** RegularExpression Id. */
  int UINT16 = 23;
  /** RegularExpression Id. */
  int UINT8 = 24;
  /** RegularExpression Id. */
  int UINT = 25;
  /** RegularExpression Id. */
  int FLOAT128 = 26;
  /** RegularExpression Id. */
  int FLOAT64 = 27;
  /** RegularExpression Id. */
  int FLOAT32 = 28;
  /** RegularExpression Id. */
  int FLOAT = 29;
  /** RegularExpression Id. */
  int CHAR = 30;
  /** RegularExpression Id. */
  int BOOL = 31;
  /** RegularExpression Id. */
  int INT_NUMBER = 32;
  /** RegularExpression Id. */
  int FLOAT_NUMBER = 33;
  /** RegularExpression Id. */
  int CHAR_VALUE = 34;
  /** RegularExpression Id. */
  int BOOL_VALUE = 35;
  /** RegularExpression Id. */
  int VARIABLE_ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "<L>",
    "<LLOW>",
    "<LHIGH>",
    "<D>",
    "<DNN>",
    "<INT_TYPE>",
    "<UINT_TYPE>",
    "<FLOAT_TYPE>",
    "<CHAR_TYPE>",
    "<BOOL_TYPE>",
    "\"int64\"",
    "\"int32\"",
    "\"int16\"",
    "\"int8\"",
    "\"int\"",
    "\"uint64\"",
    "\"uint32\"",
    "\"uint16\"",
    "\"uint8\"",
    "\"uint\"",
    "\"float128\"",
    "\"float64\"",
    "\"float32\"",
    "\"float\"",
    "\"char\"",
    "\"bool\"",
    "<INT_NUMBER>",
    "<FLOAT_NUMBER>",
    "<CHAR_VALUE>",
    "<BOOL_VALUE>",
    "<VARIABLE_ID>",
    "\"=\"",
    "\"-\"",
    "\",\"",
  };

}
