/* ERsTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. ERsTokenManager.java */
import java.io.FileInputStream;
import java.io.File;
import java.io.IOException;

/** Token Manager. */
@SuppressWarnings ("unused")
public class ERsTokenManager implements ERsConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
      debugStream.println("   No more string literal token matches are possible.");
   switch (pos)
   {
      case 0:
         if ((active0 & 0x3c000000L) != 0L)
         {
            jjmatchedKind = 36;
            return 69;
         }
         if ((active0 & 0x3e00000L) != 0L)
         {
            jjmatchedKind = 36;
            return 23;
         }
         if ((active0 & 0x1f0000L) != 0L)
         {
            jjmatchedKind = 36;
            return 45;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 36;
            return 6;
         }
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 36;
            return 2;
         }
         return -1;
      case 1:
         if ((active0 & 0x3c000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 1;
            return 68;
         }
         if ((active0 & 0x3e00000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 1;
            return 22;
         }
         if ((active0 & 0x1f0000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 1;
            return 44;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 1;
            return 5;
         }
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 1;
            return 1;
         }
         return -1;
      case 2:
         if ((active0 & 0x3c000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 2;
            }
            return 67;
         }
         if ((active0 & 0x3e00000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 2;
            }
            return 21;
         }
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 2;
            }
            return 4;
         }
         if ((active0 & 0x40000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 2;
            }
            return 0;
         }
         if ((active0 & 0x1f0000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 2;
            }
            return 43;
         }
         return -1;
      case 3:
         if ((active0 & 0x80000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 15;
               jjmatchedPos = 3;
            }
            return 18;
         }
         if ((active0 & 0x3e00000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 12;
               jjmatchedPos = 3;
            }
            return 20;
         }
         if ((active0 & 0x40000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 14;
               jjmatchedPos = 3;
            }
            return 18;
         }
         if ((active0 & 0x3c000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 3;
            }
            return 66;
         }
         if ((active0 & 0x80000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 3;
            }
            return 18;
         }
         if ((active0 & 0x20000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 3;
            }
            return 50;
         }
         if ((active0 & 0x40000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 3;
            }
            return 46;
         }
         if ((active0 & 0x10000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 3;
            }
            return 54;
         }
         return -1;
      case 4:
         if ((active0 & 0x400000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 4;
            }
            return 29;
         }
         if ((active0 & 0x3c000000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 13;
               jjmatchedPos = 4;
            }
            return 71;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 4;
            }
            return 24;
         }
         if ((active0 & 0x1000000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 12;
               jjmatchedPos = 4;
            }
            return 18;
         }
         if ((active0 & 0x200000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 36;
               jjmatchedPos = 4;
            }
            return 34;
         }
         if ((active0 & 0x70000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 11;
               jjmatchedPos = 4;
            }
            return 18;
         }
         return -1;
      case 5:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 5;
            return 76;
         }
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 5;
            return 83;
         }
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 5;
            return 70;
         }
         if ((active0 & 0xe00000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 5;
            return 18;
         }
         return -1;
      case 6:
         if ((active0 & 0x18000000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 6;
            return 18;
         }
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 6;
            return 82;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   debugStream.println("   No more string literal token matches are possible.");
   debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 44:
         return jjStopAtPos(0, 39);
      case 45:
         return jjStopAtPos(0, 38);
      case 59:
         return jjStopAtPos(0, 5);
      case 61:
         return jjStopAtPos(0, 37);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x80000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x3c000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1f0000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x3e00000L);
      default :
      debugStream.println("   No string literal matches possible.");
         return jjMoveNfa_0(3, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 1;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x3e00000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x3c000000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x1f0000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 2;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x3e00000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0xbc000000L);
      case 116:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0xf0000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 3;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 49:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 51:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000L);
      case 54:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 56:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 11, 18);
         break;
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x3c000000L);
      case 108:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 15, 18);
         break;
      case 114:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 14, 18);
         break;
      case 116:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x1e00000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 4;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 49:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 50:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 18);
         break;
      case 51:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 52:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 18);
         break;
      case 54:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 18);
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L);
      case 56:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 18);
         break;
      case 116:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x1c000000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 5;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 49:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 50:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(5, 12, 18);
         break;
      case 51:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L);
      case 52:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(5, 12, 18);
         break;
      case 54:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 12, 18);
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000L);
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 6;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 50:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 18);
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000L);
      case 52:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(6, 13, 18);
         break;
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
      debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   debugStream.println("   Possible string literal matches : { "
 +
         jjKindsForBitVector(0, active0)  + " } ");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      return 7;
   }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   switch(curChar)
   {
      case 56:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(7, 13, 18);
         break;
      default :
      debugStream.println("   No string literal matches possible.");
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   debugStream.println("   No more string literal token matches are possible.");
   debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 92;
   int i = 1;
   jjstateSet[0] = startState;
      debugStream.println("   Starting NFA to match one of : " + jjKindsForStateVector(curLexState, jjstateSet, 0, 1));
      debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 52)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  break;
               case 82:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 56)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 54)
                     jjstateSet[jjnewStateCnt++] = 34;
                  else if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 29;
                  else if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 24;
                  else if (curChar == 56)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  break;
               case 21:
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 50)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 50)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 50)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  break;
               case 83:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 32)
                        kind = 32;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if (curChar == 39)
                     { jjAddStates(3, 4); }
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 52)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 54)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 83;
                  else if (curChar == 54)
                     jjstateSet[jjnewStateCnt++] = 76;
                  else if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 52)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 54)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 54)
                     jjstateSet[jjnewStateCnt++] = 54;
                  else if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 50;
                  else if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 46;
                  else if (curChar == 56)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  break;
               case 8:
                  if (curChar == 39)
                     { jjAddStates(3, 4); }
                  break;
               case 9:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     { jjCheckNAdd(10); }
                  break;
               case 10:
                  if (curChar == 39 && kind > 34)
                     kind = 34;
                  break;
               case 12:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAdd(10); }
                  break;
               case 25:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 30:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 35:
                  if (curChar == 54)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 47:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 51:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 55:
                  if (curChar == 54)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 32)
                     kind = 32;
                  { jjCheckNAdd(61); }
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAddTwoStates(62, 63); }
                  break;
               case 63:
                  if (curChar == 46)
                     { jjCheckNAdd(64); }
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAdd(64); }
                  break;
               case 77:
                  if (curChar == 54)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 84:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 34:
               case 18:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 82:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 20:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 21:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 116)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 35;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 30;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 25;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 67:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 85;
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 78;
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 72;
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 70:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 69:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 90;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 87;
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 80;
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 74;
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 86;
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 79;
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 73;
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 6:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 45:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 58;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 56;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 52;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 48;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 66:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 84;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 77;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 71;
                  if (curChar == 116)
                  {
                     if (kind > 13)
                        kind = 13;
                  }
                  break;
               case 1:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 50:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 23:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 40;
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 37;
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 32;
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 27;
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 29:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 83:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 3:
                  if ((0x7fffffe00000000L & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 102)
                     { jjAddStates(5, 9); }
                  else if (curChar == 105)
                     { jjAddStates(10, 14); }
                  else if (curChar == 117)
                     { jjAddStates(15, 19); }
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 22:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 39;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 36;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 31;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 26;
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 76:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 24:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 71:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 5:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 54:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 46:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 4:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 108)
                  {
                     if (kind > 15)
                        kind = 15;
                  }
                  break;
               case 2:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 114)
                  {
                     if (kind > 14)
                        kind = 14;
                  }
                  break;
               case 44:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 36)
                        kind = 36;
                     { jjCheckNAdd(18); }
                  }
                  if (curChar == 116)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 55;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 51;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 47;
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 7:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 9:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAdd(10); }
                  break;
               case 11:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 12:
                  if ((0x14400010000000L & l) != 0L)
                     { jjCheckNAdd(10); }
                  break;
               case 13:
                  if (curChar == 101 && kind > 35)
                     kind = 35;
                  break;
               case 14:
                  if (curChar == 117)
                     { jjCheckNAdd(13); }
                  break;
               case 15:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if ((0x7fffffe00000000L & l) == 0L)
                     break;
                  if (kind > 36)
                     kind = 36;
                  { jjCheckNAdd(18); }
                  break;
               case 19:
                  if (curChar == 117)
                     { jjAddStates(15, 19); }
                  break;
               case 26:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 31:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 36:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 116 && kind > 12)
                     kind = 12;
                  break;
               case 40:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if (curChar == 105)
                     { jjAddStates(10, 14); }
                  break;
               case 48:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 49:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 52:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 56:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 116 && kind > 11)
                     kind = 11;
                  break;
               case 59:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 65:
                  if (curChar == 102)
                     { jjAddStates(5, 9); }
                  break;
               case 72:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 78:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 85:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 115)
                     { jjCheckNAdd(13); }
                  break;
               case 90:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 9:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if (jjmatchedKind != 0 && jjmatchedKind != 0x7fffffff)
         debugStream.println("   Currently matched the first " + (jjmatchedPos + 1) + " characters as a " + tokenImage[jjmatchedKind] + " token.");
      if ((i = jjnewStateCnt) == (startsAt = 92 - (jjnewStateCnt = startsAt)))
         return curPos;
      debugStream.println("   Possible kinds of longer matches : " + jjKindsForStateVector(curLexState, jjstateSet, startsAt, i));
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
      debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\73", null, null, null, null, null, null, null, 
null, null, null, "\151\156\164\66\64", "\151\156\164\63\62", "\151\156\164\61\66", 
"\151\156\164\70", "\151\156\164", "\165\151\156\164\66\64", "\165\151\156\164\63\62", 
"\165\151\156\164\61\66", "\165\151\156\164\70", "\165\151\156\164", "\146\154\157\141\164\61\62\70", 
"\146\154\157\141\164\66\64", "\146\154\157\141\164\63\62", "\146\154\157\141\164", "\143\150\141\162", 
"\142\157\157\154", null, null, null, null, null, "\75", "\55", "\54", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   61, 62, 63, 9, 11, 69, 75, 81, 88, 91, 45, 49, 53, 57, 59, 23, 
   28, 33, 38, 41, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      debugStream.println("Returning the <EOF> token.\n");
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
   {
      debugStream.println("Skipping character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ")");
         curChar = input_stream.BeginToken();
   }
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
      debugStream.println("Current character : " + TokenMgrError.addEscapes(String.valueOf(curChar)) + " (" + (int)curChar + ") at line " + input_stream.getEndLine() + " column " + input_stream.getEndColumn());
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
      {
         debugStream.println("   Putting back " + (curPos - jjmatchedPos - 1) + " characters into the input stream.");
         input_stream.backup(curPos - jjmatchedPos - 1);
      }
    debugStream.println("****** FOUND A " + tokenImage[jjmatchedKind] + " MATCH (" + TokenMgrError.addEscapes(new String(input_stream.GetSuffix(jjmatchedPos + 1))) + ") ******\n");
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

protected static final int[][][] statesForState = {
 {
   { 0, 18, },
   { 1, 18, },
   { 2, 18, },
   { 3, 7, 8, 16, 17, 19, 42, 60, 65, },
   { 4, 18, },
   { 5, 18, },
   { 6, 18, },
   { 3, 7, 8, 16, 17, 19, 42, 60, 65, },
   { 3, 7, 8, 16, 17, 19, 42, 60, 65, },
   { 9 },
   { 10 },
   { 11 },
   { 12 },
   { 13 },
   { 14 },
   { 15 },
   { 3, 7, 8, 16, 17, 19, 42, 60, 65, },
   { 3, 7, 8, 16, 17, 19, 42, 60, 65, },
   { 82, 18, },
   { 3, 7, 8, 16, 17, 19, 42, 60, 65, },
   { 20, 25, 30, 35, 18, },
   { 21, 26, 31, 36, 39, 18, },
   { 22, 27, 32, 37, 40, 18, },
   { 23, 28, 33, 38, 41, 18, },
   { 24, 18, },
   { 20, 25, 30, 35, 18, },
   { 21, 26, 31, 36, 39, 18, },
   { 22, 27, 32, 37, 40, 18, },
   { 23, 28, 33, 38, 41, 18, },
   { 29, 18, },
   { 20, 25, 30, 35, 18, },
   { 21, 26, 31, 36, 39, 18, },
   { 22, 27, 32, 37, 40, 18, },
   { 23, 28, 33, 38, 41, 18, },
   { 34, 18, },
   { 20, 25, 30, 35, 18, },
   { 21, 26, 31, 36, 39, 18, },
   { 22, 27, 32, 37, 40, 18, },
   { 23, 28, 33, 38, 41, 18, },
   { 21, 26, 31, 36, 39, 18, },
   { 22, 27, 32, 37, 40, 18, },
   { 23, 28, 33, 38, 41, 18, },
   { 3, 7, 8, 16, 17, 19, 42, 60, 65, },
   { 43, 47, 51, 55, 18, },
   { 44, 48, 52, 56, 58, 18, },
   { 45, 49, 53, 57, 59, 18, },
   { 46, 18, },
   { 43, 47, 51, 55, 18, },
   { 44, 48, 52, 56, 58, 18, },
   { 45, 49, 53, 57, 59, 18, },
   { 50, 18, },
   { 43, 47, 51, 55, 18, },
   { 44, 48, 52, 56, 58, 18, },
   { 45, 49, 53, 57, 59, 18, },
   { 54, 18, },
   { 43, 47, 51, 55, 18, },
   { 44, 48, 52, 56, 58, 18, },
   { 45, 49, 53, 57, 59, 18, },
   { 44, 48, 52, 56, 58, 18, },
   { 45, 49, 53, 57, 59, 18, },
   { 3, 7, 8, 16, 17, 19, 42, 60, 65, },
   { 61 },
   { 62 },
   { 63 },
   { 64 },
   { 3, 7, 8, 16, 17, 19, 42, 60, 65, },
   { 66, 72, 78, 85, 18, },
   { 67, 73, 79, 86, 18, },
   { 68, 74, 80, 87, 18, },
   { 69, 75, 81, 88, 91, 18, },
   { 70, 18, },
   { 71, 77, 84, 18, },
   { 66, 72, 78, 85, 18, },
   { 67, 73, 79, 86, 18, },
   { 68, 74, 80, 87, 18, },
   { 69, 75, 81, 88, 91, 18, },
   { 76, 18, },
   { 71, 77, 84, 18, },
   { 66, 72, 78, 85, 18, },
   { 67, 73, 79, 86, 18, },
   { 68, 74, 80, 87, 18, },
   { 69, 75, 81, 88, 91, 18, },
   { 82, 18, },
   { 83, 18, },
   { 71, 77, 84, 18, },
   { 66, 72, 78, 85, 18, },
   { 67, 73, 79, 86, 18, },
   { 68, 74, 80, 87, 18, },
   { 69, 75, 81, 88, 91, 18, },
   { 89 },
   { 90 },
   { 69, 75, 81, 88, 91, 18, },
},

};
protected static final int[][] kindForState = {
{ 
  14, 
  14, 
  14, 
  14, 
  15, 
  15, 
  15, 
  15, 
  34, 
  34, 
  34, 
  34, 
  34, 
  35, 
  35, 
  35, 
  35, 
  36, 
  36, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  12, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  11, 
  32, 
  32, 
  33, 
  33, 
  33, 
  35, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  13, 
  35, 
  35, 
  35, }
};
  int kindCnt = 0;
  protected final String jjKindsForBitVector(int i, long vec)
  {
    String retVal = "";
    if (i == 0)
       kindCnt = 0;
    for (int j = 0; j < 64; j++)
    {
       if ((vec & (1L << j)) != 0L)
       {
          if (kindCnt++ > 0)
             retVal += ", ";
          if (kindCnt % 5 == 0)
             retVal += "\n     ";
          retVal += tokenImage[i * 64 + j];
       }
    }
    return retVal;
  }


  protected final String jjKindsForStateVector(int lexState, int[] vec, int start, int end)
  {
    boolean[] kindDone = new boolean[40];
    String retVal = "";
    int cnt = 0;
    for (int i = start; i < end; i++)
    {
     if (vec[i] == -1)
       continue;
     int[] stateSet = statesForState[curLexState][vec[i]];
     for (int j = 0; j < stateSet.length; j++)
     {
       int state = stateSet[j];
       if (!kindDone[kindForState[lexState][state]])
       {
          kindDone[kindForState[lexState][state]] = true;
          if (cnt++ > 0)
             retVal += ", ";
          if (cnt % 5 == 0)
             retVal += "\n     ";
          retVal += tokenImage[kindForState[lexState][state]];
       }
     }
    }
    if (cnt == 0)
       return "{  }";
    else
       return "{ " + retVal + " }";
  }


void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public ERsTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public ERsTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 92; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffff821L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
static final long[] jjtoSpecial = {
   0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[92];
    private final int[] jjstateSet = new int[2 * 92];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
