options
{
	static = false;
	DEBUG_PARSER = true;
	DEBUG_TOKEN_MANAGER = true;
}
PARSER_BEGIN(ERs)
import java.io.FileInputStream;
import java.io.File;
import java.io.IOException;
public class ERs
{
	public static void main(String args []) throws ParseException
	{
		try
		{
			System.out.println("Lendo arquivo fonte...");
			FileInputStream fis = new FileInputStream(new File("..//JavaCC//src//fonte.txt"));
			ERs parser = new ERs(fis);
			parser.Start();
			System.out.println("Arquivo fonte processado corretamente!");
		}
		catch (IOException e)
		{
			System.out.println("Falha ao abrir arquivo fonte.");
			System.exit(0);
		}
	}
}
/*
declaration done
assignment done
expressions done
blocks {} done
if, else, else if done
while, do while done
a++; done
for done
comment done

a ? b : c
functions creation
array
class, struct
*/

PARSER_END(ERs)
SKIP : { " "| "\t" | "\n" | "\r" }

SPECIAL_TOKEN: {
  < COMMENT_LINE: "//" (~["\n","\r"])*>
}

SPECIAL_TOKEN: {
  < COMMENT_BLOCK: "/*" (~["*"])* ("*" (~["/"] (~["*"])* "*")*)* "/" >
}

TOKEN : {
    < IF : "if" > | < ELSE : "else" > | < WHILE : "while" > | < FOR : "for" > | < DO : "do" >
}
TOKEN : {
  < EOL : ";" >
}
TOKEN : {
	<#L : ["a"-"z", "A"-"Z"]>
}
TOKEN : {
	<#LLOW : [ "a"-"z"]>
}
TOKEN : {
	<#LHIGH : [ "A"-"Z"]>
}
TOKEN : {
  <#D : [ "0"-"9" ]>
}
TOKEN : {
  <#DNN : [ "1"-"9" ]>
}
TOKEN : {
  	<TYPE: <INT_TYPE> | <UINT_TYPE> | <FLOAT_TYPE> | <CHAR_TYPE> | <BOOL_TYPE>> | 
  	<INT_TYPE : <INT8> | <INT16> | <INT32> | <INT64> | <INT>> |
  	<UINT_TYPE : <UINT8> | <UINT16> | <UINT32> | <UINT64> | <UINT>> |
  	<FLOAT_TYPE : <FLOAT> | <FLOAT32> | <FLOAT64> | <FLOAT128>> |
  	<CHAR_TYPE : <CHAR>> |
  	<BOOL_TYPE : <BOOL>> |

    < INT64: "int64" > | < INT32: "int32" > | < INT16: "int16" > | < INT8: "int8" > | < INT: "int" > |

    < UINT64: "uint64" > | < UINT32: "uint32" > | < UINT16: "uint16" > | < UINT8: "uint8" > | < UINT: "uint" > |

    < FLOAT128: "float128" > | < FLOAT64: "float64" > | < FLOAT32: "float32" > | < FLOAT: "float" > |
    < CHAR: "char" > |
    < BOOL: "bool" >
}

TOKEN : {
  <INT_NUMBER : (<D>)+>
}
TOKEN : {
  <FLOAT_NUMBER : <INT_NUMBER>("."<INT_NUMBER>)?>
}
TOKEN : {
  < CHAR_VALUE :
    "'"
    (
      ~["\\", "'"]
      |
      "\\" ( ["n","t","r","\\","'","\""] )
    )
    "'"
  >
}
TOKEN : {
	<BOOL_VALUE : ( "true" | "false" )>
}
TOKEN : {
  <VARIABLE_ID : <LLOW>(<L> | <D>)* >
}

TOKEN : {
    <ASSIGNMENT : "=" > |
    <ASSIGNMENT_CP: "<<=" | ">>=" | "+=" | "-=" | "*=" | "/=" | "%=" | "&=" | "|=" | "^=" > |
    <INCREMENT : "++" | "--"> |
    <ARITHMETIC_OP : "<<" | ">>" | "||" | "&&" | "+" | "-" | "/" | "%" | "|" | "^" > |
    <RELATIONAL_OP : "<" | ">" | "<=" | ">=" | "==" | "!=" > |
    <SINGLE_ARITHMETIC_OP : "~" | "!" | "+" | "-" > |
    <ACCESS_OP : "->" | "."> |
    <MEMORY_ACCESS_OP_AND_ARITHMETIC:  "*" | "&" >
}

void function_call() : {} {
	<VARIABLE_ID>"("
	(
		expression()
		(
			"," expression()
		)*
	)?
	")"
}

void access_or_call() : {} {
  	(<MEMORY_ACCESS_OP_AND_ARITHMETIC>)?
  	(<INCREMENT>)?
    (
        LOOKAHEAD(2)
        function_call() |
        <VARIABLE_ID>
    )
    (
        <ACCESS_OP>
        (
            LOOKAHEAD(2)
			function_call() |
            <VARIABLE_ID>
        )
    )*
  	(<INCREMENT>)?
}

void value() : {} {
	(<SINGLE_ARITHMETIC_OP>)?
	(
	  	access_or_call() |
	  	(
  	 	  	(<INCREMENT>)?
  			(<INT_NUMBER> | <FLOAT_NUMBER>)
  	 	  	(<INCREMENT>)?
	  	) |
		<CHAR_VALUE> |
		<BOOL_VALUE> |
		("(" expression() ")")
	)
}

void expression() : {} {
    value()
    (
        (<ARITHMETIC_OP>|<RELATIONAL_OP >|<MEMORY_ACCESS_OP_AND_ARITHMETIC>)
        value()
    )*
}

void assignment() : {} {
    <ASSIGNMENT> expression()
}

void assignment_call() : {} {
  	
  	access_or_call()
  	(  	  	(
	  	 	<ASSIGNMENT_CP>|<ASSIGNMENT >
	  	)
	 	expression()
	)?
}

void declare_vars() : {} {
 	<TYPE> <VARIABLE_ID> (assignment())?
  	((",")<VARIABLE_ID>(assignment())?)*
}

void create_block() : {} {
	"{"
	(command_call())*
	"}"
}

void if_command() : {} {
    <IF> "(" expression() ")"
    create_block()
    (
        <ELSE>
        (
            LOOKAHEAD(<IF>)
            if_command()
        |
            create_block()
        )
    )?
}

void for_command() : {} {
	<FOR>"("
	((declare_vars() | assignment_call()))? <EOL>
	(expression())? <EOL>
	(expression())? ")"
	create_block()
}

void while_command() : {} {
    <WHILE> "(" expression() ")"
    create_block()
}

void do_while_command() : {} {
    <DO>
    create_block()
    <WHILE> "(" expression() ")" <EOL>
}

void command_call() : {} {
    (
        (
            (
                assignment_call() |
                declare_vars()
            ) <EOL>
        ) |
        if_command() |
        do_while_command() |
        while_command() |
        for_command() |
        create_block()
    )
}

void Start() : {} {
	(command_call())*
	<EOF>
}